// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DownloadImages(arg1:string):Promise<string>;

export function Scrape(arg1:string):Promise<Array<main.Wallpaper>>;
