// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadImages(arg1) {
  return window['go']['main']['App']['DownloadImages'](arg1);
}

export function Scrape(arg1) {
  return window['go']['main']['App']['Scrape'](arg1);
}
